# -------------------------------------------------------
# DontRepair v. 1.0
# Разработано vk.com/daedal_dev специально для QueerZizz
# -------------------------------------------------------

# --------------------------------------- Пермишены ------------------------------------------------------
# dontrepair.prevent - Запрещает группе чинить помеченные предметы
# dontrepair.allow - Разрешает группе чинить помеченные предметы
# dontrepair.admin - Разрешает выполнение команды /dontrepair для пометки предметов, которые нельзя чинить
# --------------------------------------------------------------------------------------------------------

#  --------------------------------------- Команды -------------------------------------------------------
# /dontrepair tag - Пометить предмет как неремонтируемый (Необходимо держать предмет в руке)
# /dontrepair untag - Пометить предмет как ремонтируемый (Необходимо держать предмет в руке)
# /dontrepair reload - Перезагрузить конфигурацию плагина
# --------------------------------------------------------------------------------------------------------

# Сообщение, отправляемое игроку, который пытается починить предмет
message: "&cВы не можете чинить предметы из кита!"
